# Generated by Django 6.1.1 on 2026-10-01 13:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerSkillBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=64)),
                ('baseline_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('confidence', models.FloatField(default=0.35, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('direct_evidence', models.BooleanField(default=False)),
                ('trend', models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('error_counts', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_baselines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'updated_at'], name='skill_user_updated_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'skill'), name='uniq_user_skill_baseline')],
            },
        ),
        migrations.CreateModel(
            name='PracticeExercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('age_group', models.CharField(choices=[('under_12', 'Under 12'), ('12_15', '12 to 15'), ('16_18', '16 to 18'), ('19_plus', '19 or older')], max_length=16)),
                ('bank_version', models.CharField(max_length=80)),
                ('target_skill', models.CharField(max_length=64)),
                ('difficulty', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('source_exercise_id', models.CharField(max_length=100)),
                ('response_type', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField()),
                ('prompt', models.TextField()),
                ('content_data', models.JSONField(default=dict)),
                ('private_scoring', models.JSONField(default=dict)),
                ('content_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='practice_user_created_idx')],
            },
        ),
    ]
