# Generated by Django 6.1.1 on 2026-10-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalized_practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerskillbaseline',
            name='metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
