# Generated by Django 6.1.1 on 2026-10-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalized_practice', '0002_learnerskillbaseline_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceexercise',
            name='secondary_skill',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
