# Generated by Django 6.1.1 on 2026-10-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalized_practice', '0004_progressattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressattempt',
            name='correct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
