# Generated by Django 6.1.1 on 2026-10-01 22:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age_group', models.CharField(blank=True, choices=[('under_12', 'Under 12'), ('12_15', '12-15'), ('16_18', '16-18'), ('19_plus', '19+')], default='', max_length=10)),
                ('estimated_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('estimated_voice_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('assessment_type', models.CharField(blank=True, choices=[('assessment', 'Assessment'), ('exercise', 'Exercise'), ('real_life', 'Real Life')], default='', max_length=100)),
            ],
            options={
                'db_table': 'assessments',
            },
        ),
        migrations.CreateModel(
            name='AssessmentExcercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('kind', models.CharField(blank=True, choices=[('phoneme_manipulation', 'Phoneme Manipulation'), ('letter_sound', 'Letter Sound'), ('word_reading_sample', 'Word Reading Sample'), ('visual_retrieval_speed', 'Visual Retrieval Speed'), ('reading_fluency', 'Reading Fluency'), ('spelling', 'Spelling'), ('comprehension', 'comprehension'), ('working_memory', 'working_memory')], default='', max_length=100)),
                ('skill', models.CharField(blank=True, choices=[('phonological_awareness', 'Phonological Awareness'), ('letter_sound_association', 'Letter Sound Association'), ('decoding', 'Decoding'), ('word_recognition', 'Word Recognition'), ('naming_speed', 'Naming Speed'), ('reading_fluency', 'Reading Fluency'), ('spelling', 'Spelling'), ('comprehension', 'Comprehension'), ('working_memory', 'Working Memory')], default='', max_length=100)),
                ('difficulty_level', models.IntegerField(blank=True, null=True)),
                ('response_type', models.CharField(blank=True, choices=[('single_choice_set', 'Single Choice Set'), ('spoken', 'Spoken'), ('reading_fluency', 'Reading Fluency'), ('spelling', 'Spelling'), ('comprehension', 'Comprehension'), ('sequence', 'Sequence')], default='', max_length=100)),
                ('instruction', models.TextField(blank=True, default='')),
                ('content_data', models.JSONField(blank=True, null=True)),
                ('answers', models.JSONField(blank=True, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excercises', to='assessments.assessment')),
            ],
            options={
                'db_table': 'assessment_excercises',
            },
        ),
    ]
