# Generated by Django 6.1.1 on 2026-10-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
