# Generated by Django 6.1.1 on 2026-10-02 03:09

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessment_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonological_awareness', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('letter_sound_association', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('decoding', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('word_recognition', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('naming_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reading_fluency', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('spelling', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comprehension', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('working_memory', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error_types', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='assessments.assessment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_evaluations', to=settings.AUTH_USER_MODEL)),
                ('updated_skills', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_evaluation', to='assessments.skillhistory')),
            ],
            options={
                'db_table': 'assessment_evaluations',
            },
        ),
    ]
