# Generated by Django 6.1.1 on 2026-10-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessment_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentexcercise',
            name='exercise_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='assessmentexcercise',
            name='response_type',
            field=models.CharField(blank=True, choices=[('single_choice_set', 'Single Choice Set'), ('spoken', 'Spoken'), ('typed_text', 'Typed Text'), ('sequence', 'Sequence')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assessmentexcercise',
            name='skill',
            field=models.CharField(blank=True, choices=[('phonological_awareness', 'Phonological Awareness'), ('letter_sound', 'Letter Sound'), ('letter_sound_association', 'Letter Sound Association'), ('decoding_and_word_recognition', 'Decoding and Word Recognition'), ('decoding', 'Decoding'), ('word_recognition', 'Word Recognition'), ('naming_speed', 'Naming Speed'), ('reading_fluency', 'Reading Fluency'), ('spelling', 'Spelling'), ('comprehension', 'Comprehension'), ('working_memory', 'Working Memory')], default='', max_length=100),
        ),
    ]
