# Generated by Django 6.1.1 on 2026-10-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_skillhistory_assessmentevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentevaluation',
            name='answers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
