# Generated by Django 6.1.1 on 2026-10-02 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assessmentexcercise_exercise_id_and_more'),
        ('assessments', '0004_assessmentevaluation_answers'),
    ]

    operations = [
    ]
