# Generated by Django 6.1.1 on 2026-10-02 07:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_assessment_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RealLifeExercise',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('age_group', models.CharField(choices=[('under_12', 'Under 12'), ('12_15', '12-15'), ('16_18', '16-18'), ('19_plus', '19+')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('context', models.CharField(max_length=255)),
                ('information', models.JSONField(default=list)),
                ('question', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('correct_answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RealLifeExerciseAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_date', models.DateField()),
                ('slot', models.PositiveSmallIntegerField()),
                ('exercise_data', models.JSONField()),
                ('answer', models.TextField(blank=True, default='')),
                ('correct', models.BooleanField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='assessments.reallifeexercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_life_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['assigned_date', 'slot'],
                'constraints': [models.UniqueConstraint(fields=('user', 'assigned_date', 'slot'), name='real_life_unique_daily_slot'), models.UniqueConstraint(fields=('user', 'assigned_date', 'exercise'), name='real_life_unique_daily_exercise'), models.CheckConstraint(condition=models.Q(('slot__gte', 1), ('slot__lte', 3)), name='real_life_three_daily_slots')],
            },
        ),
    ]
