# Generated by Django 6.1.1 on 2026-10-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_reallifeexercise_reallifeexerciseattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(blank=True, choices=[('assessment', 'Assessment'), ('exercise', 'Exercise')], default='', max_length=100),
        ),
    ]
