# Generated by Django 6.1.1 on 2026-10-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assessment_completed',
            field=models.BooleanField(default=False),
        ),
    ]
