# Generated by Django 6.1.1 on 2026-10-01 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_assessment_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
