# Generated by Django 6.1.1 on 2026-10-01 13:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='age_group',
            field=models.CharField(blank=True, choices=[('under_12', 'Under 12'), ('12_15', '12-15'), ('16_18', '16-18'), ('19_plus', '19+')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_focus',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='learning',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list),
        ),
    ]
