# Generated by Django 6.1.1 on 2026-10-01 15:18

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_learning_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_font', models.CharField(choices=[('default', 'Default'), ('lexend', 'Lexend'), ('opens_dyslexic', 'OpenDyslexic')], default='default', max_length=100)),
                ('font_size', models.CharField(choices=[('comfortable', 'Comfortable'), ('large', 'Large'), ('x_large', 'Extra Large')], default='comfortable', max_length=100)),
                ('letter_spacing', models.CharField(choices=[('standard', 'Standard'), ('wide', 'Wide'), ('wider', 'Wider')], default='standard', max_length=100)),
                ('line_spacing', models.CharField(choices=[('standard', 'Standard'), ('relaxed', 'Relaxed'), ('wide', 'Wide')], default='standard', max_length=100)),
                ('text_to_speech', models.BooleanField(default=False)),
                ('current_line_highlight', models.BooleanField(default=True)),
                ('reduced_clutter', models.BooleanField(default=False)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonological_awareness', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('letter_sound_association', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('decoding', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('word_recognition', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('naming_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reading_fluency', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('spelling', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comprehension', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('working_memory', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='current_focus',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='learning',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='profile',
            name='learning_goal',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferences',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='user.preferences'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='user.skill'),
        ),
    ]
