# Generated by Django 6.1.1 on 2026-10-01 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_age_years'),
        ('user', '0005_learner_profile_models'),
    ]

    operations = [
    ]
