# Generated by Django 6.1.1 on 2026-10-01 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_merge_20261001_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age_years',
        ),
    ]
