# Generated by Django 6.1.1 on 2026-10-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_profile_age_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='on_bording_completed',
            field=models.BooleanField(default=False),
        ),
    ]
