# Generated by Django 6.1.1 on 2026-10-01 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_on_bording_completed'),
        ('user', '0008_user_onboarding_completed'),
    ]

    operations = [
    ]
