# Generated by Django 6.1.1 on 2026-10-02 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_merge_20261001_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='onboarding_completed',
        ),
    ]
