# Generated by Django 6.1.1 on 2026-10-02 08:31

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealLifeSet',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('age_group', models.CharField(choices=[('under_12', 'Under 12'), ('12_15', '12-15'), ('16_18', '16-18'), ('19_plus', '19+')], max_length=10)),
                ('category', models.TextField()),
            ],
            options={
                'db_table': 'real_life_sets',
            },
        ),
        migrations.CreateModel(
            name='RealLifeSetExercise',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('context', models.CharField(max_length=255)),
                ('information', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list)),
                ('question', models.TextField()),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list)),
                ('correct_answer', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list)),
                ('note', models.TextField(blank=True, default='')),
                ('real_life_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='real_life_set.reallifeset')),
            ],
            options={
                'db_table': 'real_life_set_exercises',
            },
        ),
    ]
