# Generated by Django 6.1.1 on 2026-10-02 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_life_set', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RealLifeSetEvaluation',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answers', models.JSONField(default=dict)),
                ('real_life_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='real_life_set.reallifeset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_life_set_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'real_life_set_evaluations',
            },
        ),
    ]
