# Generated by Django 6.1.1 on 2026-10-02 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_life_set', '0002_reallifesetevaluation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reallifesetexercise',
            name='note',
        ),
    ]
